package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestHumanReadableSize(t *testing.T) {
	cases := []struct {
		size int64
		want string
	}{
		{0, "0 B"},
		{512, "512 B"},
		{1023, "1023 B"},
		{1024, "1.0 KB"},
		{1536, "1.5 KB"},
		{1024 * 1024, "1.0 MB"},
		{5 * 1024 * 1024, "5.0 MB"},
		{1024 * 1024 * 1024, "1.0 GB"},
		{2 << 30, "2.0 GB"},
	}
	for _, c := range cases {
		if got := humanReadableSize(c.size); got != c.want {
			t.Errorf("humanReadableSize(%d) = %q, want %q", c.size, got, c.want)
		}
	}
}

func TestNormalizedFilename(t *testing.T) {
	cases := []struct{ in, want string }{
		{"plain.gcode", "plain.gcode"},
		{"../../etc/passwd", "etc/passwd"},
		{"/abs/path/file.gcode", "abs/path/file.gcode"},
		{`\\server\share\test.gcode`, "server\\share\\test.gcode"},
		{"~/file.nc", "file.nc"},
		{"..a.gcode", "a.gcode"},
		// drive letters are not stripped (leading-run regex)
		{`C:\Users\test.gcode`, `C:\Users\test.gcode`},
	}
	for _, c := range cases {
		if got := normalizedFilename(c.in); got != c.want {
			t.Errorf("normalizedFilename(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestShouldBeFix(t *testing.T) {
	cases := []struct {
		name string
		want bool
	}{
		{"model.gcode", true},
		{"MODEL.GCODE", true},
		{"part.nc", false},
		{"part.cnc", false},
		{"fw.bin", false},
		{"readme.txt", false},
		{"noext", false},
	}
	for _, c := range cases {
		if got := shouldBeFix(c.name); got != c.want {
			t.Errorf("shouldBeFix(%q) = %v, want %v", c.name, got, c.want)
		}
	}
}

func TestParseEnvHelpers(t *testing.T) {
	t.Setenv("SM_TEST_INT", "42")
	if got := parseIntEnv("SM_TEST_INT", 0); got != 42 {
		t.Errorf("parseIntEnv = %d, want 42", got)
	}
	t.Setenv("SM_TEST_INT", "notanumber")
	if got := parseIntEnv("SM_TEST_INT", 7); got != 7 {
		t.Errorf("parseIntEnv invalid = %d, want 7", got)
	}
	if got := parseIntEnv("SM_TEST_MISSING", 7); got != 7 {
		t.Errorf("parseIntEnv missing = %d, want 7", got)
	}

	t.Setenv("SM_TEST_BOOL", "true")
	if !parseBoolEnv("SM_TEST_BOOL", false) {
		t.Error("parseBoolEnv = false, want true")
	}
	t.Setenv("SM_TEST_BOOL", "bogus")
	if !parseBoolEnv("SM_TEST_BOOL", true) {
		t.Error("parseBoolEnv invalid should fall back to default true")
	}

	t.Setenv("SM_TEST_DUR", "3s")
	if got := parseDurationEnv("SM_TEST_DUR", time.Second); got != 3*time.Second {
		t.Errorf("parseDurationEnv = %v, want 3s", got)
	}
	t.Setenv("SM_TEST_DUR", "xyz")
	if got := parseDurationEnv("SM_TEST_DUR", 4*time.Second); got != 4*time.Second {
		t.Errorf("parseDurationEnv invalid = %v, want 4s", got)
	}
}

// realistic multi-tool g-code with the PrusaSlicer metadata header that
// SMFix's ExtractHeader requires
const sampleGcode = `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; bed_shape = 0x0,320x350
; first_layer_temperature = 215, 220
; first_layer_bed_temperature = 60, 65
; nozzle_diameter = 0.4, 0.4
; layer_height = 0.2
; total_layer_number = 150
; filament_type = PLA,ABS
; filament used [mm] = 5000, 3000
; filament used [g] = 12.5, 7.5
; estimated printing time (normal mode) = 1h 30m 0s
; retract_length = 1.2, 1.5
; retract_length_toolchange = 3.0, 3.5
; max_print_speed = 100
; min_x = 10
; min_y = 20
; min_z = 0.2
; max_x = 300
; max_y = 330
; max_z = 50.4
; printer_notes = Don't lose focus!
G28
T0
M104 S210
G1 X100 Y100 E1 F3000
G1 X101 Y100 E2 F3000
M104 S0
T1
M104 S200
G1 X100 Y101 E3 F3000
M84
`

func TestPostProcessAndPostProcessToEquivalent(t *testing.T) {
	in := strings.NewReader(sampleGcode)

	out, err := postProcess(strings.NewReader(sampleGcode))
	if err != nil {
		t.Fatalf("postProcess: %v", err)
	}

	var buf bytes.Buffer
	if err := postProcessTo(&buf, in); err != nil {
		t.Fatalf("postProcessTo: %v", err)
	}
	if !bytes.Equal(out, buf.Bytes()) {
		t.Error("postProcess and postProcessTo outputs differ")
	}
}

func TestPostProcessMarksFixedFile(t *testing.T) {
	out, err := postProcess(strings.NewReader(sampleGcode))
	if err != nil {
		t.Fatalf("postProcess: %v", err)
	}
	if !bytes.Contains(out, []byte("; Postprocessed by smfix")) {
		t.Error("output missing smfix marker")
	}
	if len(out) == 0 {
		t.Error("output is empty")
	}
}

func TestPostProcessIdempotent(t *testing.T) {
	once, err := postProcess(strings.NewReader(sampleGcode))
	if err != nil {
		t.Fatalf("first pass: %v", err)
	}
	twice, err := postProcess(bytes.NewReader(once))
	if err != nil {
		t.Fatalf("second pass: %v", err)
	}
	// an already-fixed file takes the isFixed passthrough path, so from the
	// second pass on the output must be byte-stable
	third, err := postProcess(bytes.NewReader(twice))
	if err != nil {
		t.Fatalf("third pass: %v", err)
	}
	if !bytes.Equal(twice, third) {
		t.Error("postProcess is not stable for already-fixed files")
	}
	if !bytes.Contains(twice, []byte("; Postprocessed by smfix")) {
		t.Error("second pass lost the smfix marker")
	}
	_ = once
}

func TestPostProcessEmptyInput(t *testing.T) {
	// empty input cannot satisfy ExtractHeader's metadata requirements,
	// so the caller falls back to the raw file (matches production behavior:
	// "G-Code fix error(ignored)" then original content is uploaded)
	if _, err := postProcess(strings.NewReader("")); err == nil {
		t.Error("expected error for empty input")
	}
}

func TestPreprocessToOutputDir(t *testing.T) {
	dir := t.TempDir()
	old := OutputDir
	OutputDir = dir
	defer func() { OutputDir = old }()

	input := sampleGcode
	fixedPath, err := preprocessToOutputDir(strings.NewReader(input), "model.gcode", true)
	if err != nil {
		t.Fatalf("preprocessToOutputDir: %v", err)
	}
	if fixedPath == "" {
		t.Fatal("fixedPath is empty")
	}

	orig, err := os.ReadFile(filepath.Join(dir, "model.gcode"))
	if err != nil {
		t.Fatalf("original not saved: %v", err)
	}
	if string(orig) != input {
		t.Errorf("original content = %q, want %q", orig, input)
	}

	fixed, err := os.ReadFile(fixedPath)
	if err != nil {
		t.Fatalf("fixed file missing: %v", err)
	}
	if len(fixed) == 0 {
		t.Error("fixed file is empty")
	}
}

func TestPreprocessToOutputDirNoOriginal(t *testing.T) {
	dir := t.TempDir()
	old := OutputDir
	OutputDir = dir
	defer func() { OutputDir = old }()

	fixedPath, err := preprocessToOutputDir(strings.NewReader(sampleGcode), "model.gcode", false)
	if err != nil {
		t.Fatalf("preprocessToOutputDir: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "model.gcode")); !os.IsNotExist(err) {
		t.Error("original file should not be saved when saveOriginal=false")
	}
	if fi, err := os.Stat(fixedPath); err != nil || fi.Size() == 0 {
		t.Errorf("fixed file missing or empty: %v", err)
	}
}

func TestTempDirPrecedence(t *testing.T) {
	restoreOutputDir := OutputDir
	defer func() { OutputDir = restoreOutputDir }()

	dir := t.TempDir()

	// env wins over everything
	OutputDir = dir
	t.Setenv("SM2UPLOAD_TMPDIR", dir+"/env")
	if got := tempDir(); got != dir+"/env" {
		t.Errorf("tempDir = %q, want env override", got)
	}

	// env beats OutputDir even when both set... env unset -> OutputDir
	os.Unsetenv("SM2UPLOAD_TMPDIR")
	if got := tempDir(); got != dir {
		t.Errorf("tempDir = %q, want OutputDir", got)
	}

	// neither set -> empty (system default)
	OutputDir = ""
	if got := tempDir(); got != "" {
		t.Errorf("tempDir = %q, want empty", got)
	}
}

func TestSweepStaleSpools(t *testing.T) {
	dir := t.TempDir()
	stale := []string{
		filepath.Join(dir, "sm2upload-123.spool"),
		filepath.Join(dir, "sm2upload-abc.multipart"),
	}
	for _, p := range stale {
		if err := os.WriteFile(p, []byte("junk"), 0644); err != nil {
			t.Fatal(err)
		}
	}
	keep := filepath.Join(dir, "sm2uploadkeep.txt") // prefix without dash: must survive
	if err := os.WriteFile(keep, []byte("keep"), 0644); err != nil {
		t.Fatal(err)
	}
	keep2 := filepath.Join(dir, "unrelated.gcode")
	if err := os.WriteFile(keep2, []byte("keep"), 0644); err != nil {
		t.Fatal(err)
	}

	t.Setenv("SM2UPLOAD_TMPDIR", dir)
	sweepStaleSpools()

	for _, p := range stale {
		if _, err := os.Stat(p); !os.IsNotExist(err) {
			t.Errorf("stale spool not removed: %s", p)
		}
	}
	for _, p := range []string{keep, keep2} {
		if _, err := os.Stat(p); err != nil {
			t.Errorf("sweep removed a file it must not touch: %s", p)
		}
	}
}

func TestEnsureOutputDir(t *testing.T) {
	restoreOutputDir := OutputDir
	defer func() { OutputDir = restoreOutputDir }()

	// disabled: no-op
	OutputDir = ""
	if err := ensureOutputDir(); err != nil {
		t.Fatalf("ensureOutputDir disabled: %v", err)
	}

	// missing directory gets created
	dir := filepath.Join(t.TempDir(), "nested", "out")
	OutputDir = dir
	if err := ensureOutputDir(); err != nil {
		t.Fatalf("ensureOutputDir: %v", err)
	}
	if fi, err := os.Stat(dir); err != nil || !fi.IsDir() {
		t.Errorf("output dir not created: %v", err)
	}

	// spool files can now be created in it (regression: nofix upload with
	// a fresh -output dir used to fail in os.CreateTemp)
	if f, err := os.CreateTemp(tempDir(), "sm2upload-*.spool"); err != nil {
		t.Errorf("CreateTemp in fresh output dir: %v", err)
	} else {
		f.Close()
		os.Remove(f.Name())
	}

	// parent is a file -> error
	fileAsParent := filepath.Join(t.TempDir(), "file")
	if err := os.WriteFile(fileAsParent, []byte("x"), 0644); err != nil {
		t.Fatal(err)
	}
	OutputDir = filepath.Join(fileAsParent, "sub")
	if err := ensureOutputDir(); err == nil {
		t.Error("expected error when parent is a file")
	}
}

func TestPreprocessToOutputDirDisabled(t *testing.T) {
	old := OutputDir
	OutputDir = ""
	defer func() { OutputDir = old }()

	fixedPath, err := preprocessToOutputDir(strings.NewReader(sampleGcode), "model.gcode", true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if fixedPath != "" {
		t.Errorf("fixedPath = %q, want empty", fixedPath)
	}
}
